package utils

import models.Language

val languageList = mutableListOf(
    Language("af", "Afrikaans"),
    Language("agq", "Aghem"),
    Language("ak", "Akan"),
    Language("sq", "Albanian"),
    Language("am", "Amharic"),
    Language("ar", "Arabic"),
    Language("hy", "Armenian"),
    Language("as", "Assamese"),
    Language("ast", "Asturian"),
    Language("asa", "Asu"),
    Language("az", "Azerbaijani"),
    Language("ksf", "Bafia"),
    Language("bm", "Bambara"),
    Language("bn", "Bangla"),
    Language("bas", "Basaa"),
    Language("eu", "Basque"),
    Language("be", "Belarusian"),
    Language("bem", "Bemba"),
    Language("bez", "Bena"),
    Language("brx", "Bodo"),
    Language("bs", "Bosnian"),
    Language("br", "Breton"),
    Language("bg", "Bulgarian"),
    Language("my", "Burmese"),
    Language("yue", "Cantonese"),
    Language("ca", "Catalan"),
    Language("ceb", "Cebuano"),
    Language("tzm", "Central Atlas Tamazight"),
    Language("ckb", "Central Kurdish"),
    Language("ccp", "Chakma"),
    Language("ce", "Chechen"),
    Language("chr", "Cherokee"),
    Language("cgg", "Chiga"),
    Language("zh", "Chinese"),
    Language("ksh", "Colognian"),
    Language("kw", "Cornish"),
    Language("hr", "Croatian"),
    Language("cs", "Czech"),
    Language("da", "Danish"),
    Language("doi", "Dogri"),
    Language("dua", "Duala"),
    Language("nl", "Dutch"),
    Language("dz", "Dzongkha"),
    Language("ebu", "Embu"),
    Language("en", "English"),
    Language("eo", "Esperanto"),
    Language("et", "Estonian"),
    Language("ee", "Ewe"),
    Language("ewo", "Ewondo"),
    Language("fo", "Faroese"),
    Language("fil", "Filipino"),
    Language("fi", "Finnish"),
    Language("fr", "French"),
    Language("fur", "Friulian"),
    Language("ff", "Fulah"),
    Language("gl", "Galician"),
    Language("lg", "Ganda"),
    Language("ka", "Georgian"),
    Language("de", "German"),
    Language("el", "Greek"),
    Language("gu", "Gujarati"),
    Language("guz", "Gusii"),
    Language("ha", "Hausa"),
    Language("haw", "Hawaiian"),
    Language("he", "Hebrew"),
    Language("hi", "Hindi"),
    Language("hu", "Hungarian"),
    Language("is", "Icelandic"),
    Language("ig", "Igbo"),
    Language("smn", "Inari Sami"),
    Language("id", "Indonesian"),
    Language("ia", "Interlingua"),
    Language("ga", "Irish"),
    Language("it", "Italian"),
    Language("ja", "Japanese"),
    Language("jv", "Javanese"),
    Language("dyo", "Jola-Fonyi"),
    Language("kea", "Kabuverdianu"),
    Language("kab", "Kabyle"),
    Language("kkj", "Kako"),
    Language("kl", "Kalaallisut"),
    Language("kln", "Kalenjin"),
    Language("kam", "Kamba"),
    Language("kn", "Kannada"),
    Language("ks", "Kashmiri"),
    Language("kk", "Kazakh"),
    Language("km", "Khmer"),
    Language("ki", "Kikuyu"),
    Language("rw", "Kinyarwanda"),
    Language("kok", "Konkani"),
    Language("ko", "Korean"),
    Language("khq", "Koyra Chiini"),
    Language("ses", "Koyraboro Senni"),
    Language("ku", "Kurdish"),
    Language("nmg", "Kwasio"),
    Language("ky", "Kyrgyz"),
    Language("lkt", "Lakota"),
    Language("lag", "Langi"),
    Language("lo", "Lao"),
    Language("lv", "Latvian"),
    Language("ln", "Lingala"),
    Language("lt", "Lithuanian"),
    Language("nds", "Low German"),
    Language("dsb", "Lower Sorbian"),
    Language("lu", "Luba-Katanga"),
    Language("luo", "Luo"),
    Language("lb", "Luxembourgish"),
    Language("luy", "Luyia"),
    Language("mk", "Macedonian"),
    Language("jmc", "Machame"),
    Language("mai", "Maithili"),
    Language("mgh", "Makhuwa-Meetto"),
    Language("kde", "Makonde"),
    Language("mg", "Malagasy"),
    Language("ms", "Malay"),
    Language("ml", "Malayalam"),
    Language("mt", "Maltese"),
    Language("mni", "Manipuri"),
    Language("gv", "Manx"),
    Language("mi", "Maori"),
    Language("mr", "Marathi"),
    Language("mas", "Masai"),
    Language("mzn", "Mazanderani"),
    Language("mer", "Meru"),
    Language("mgo", "Metaʼ"),
    Language("mn", "Mongolian"),
    Language("mfe", "Morisyen"),
    Language("mua", "Mundang"),
    Language("naq", "Nama"),
    Language("ne", "Nepali"),
    Language("nnh", "Ngiemboon"),
    Language("jgo", "Ngomba"),
    Language("pcm", "Nigerian Pidgin"),
    Language("nd", "North Ndebele"),
    Language("lrc", "Northern Luri"),
    Language("se", "Northern Sami"),
    Language("no", "Norwegian"),
    Language("nb", "Norwegian Bokmål"),
    Language("nn", "Norwegian Nynorsk"),
    Language("nus", "Nuer"),
    Language("nyn", "Nyankole"),
    Language("or", "Odia"),
    Language("om", "Oromo"),
    Language("os", "Ossetic"),
    Language("ps", "Pashto"),
    Language("fa", "Persian"),
    Language("pl", "Polish"),
    Language("pt", "Portuguese"),
    Language("pa", "Punjabi"),
    Language("qu", "Quechua"),
    Language("ro", "Romanian"),
    Language("rm", "Romansh"),
    Language("rof", "Rombo"),
    Language("rn", "Rundi"),
    Language("ru", "Russian"),
    Language("rwk", "Rwa"),
    Language("sah", "Sakha"),
    Language("saq", "Samburu"),
    Language("sg", "Sango"),
    Language("sbp", "Sangu"),
    Language("sa", "Sanskrit"),
    Language("sat", "Santali"),
    Language("gd", "Scottish Gaelic"),
    Language("seh", "Sena"),
    Language("sr", "Serbian"),
    Language("ksb", "Shambala"),
    Language("sn", "Shona"),
    Language("ii", "Sichuan Yi"),
    Language("sd", "Sindhi"),
    Language("si", "Sinhala"),
    Language("sk", "Slovak"),
    Language("sl", "Slovenian"),
    Language("xog", "Soga"),
    Language("so", "Somali"),
    Language("es", "Spanish"),
    Language("zgh", "Standard Moroccan Tamazight"),
    Language("su", "Sundanese"),
    Language("sw", "Swahili"),
    Language("sv", "Swedish"),
    Language("gsw", "Swiss German"),
    Language("shi", "Tachelhit"),
    Language("dav", "Taita"),
    Language("tg", "Tajik"),
    Language("ta", "Tamil"),
    Language("twq", "Tasawaq"),
    Language("tt", "Tatar"),
    Language("te", "Telugu"),
    Language("teo", "Teso"),
    Language("th", "Thai"),
    Language("bo", "Tibetan"),
    Language("ti", "Tigrinya"),
    Language("to", "Tongan"),
    Language("tr", "Turkish"),
    Language("tk", "Turkmen"),
    Language("uk", "Ukrainian"),
    Language("hsb", "Upper Sorbian"),
    Language("ur", "Urdu"),
    Language("ug", "Uyghur"),
    Language("uz", "Uzbek"),
    Language("vai", "Vai"),
    Language("vi", "Vietnamese"),
    Language("vun", "Vunjo"),
    Language("wae", "Walser"),
    Language("cy", "Welsh"),
    Language("fy", "Western Frisian"),
    Language("wo", "Wolof"),
    Language("xh", "Xhosa"),
    Language("yav", "Yangben"),
    Language("yi", "Yiddish"),
    Language("yo", "Yoruba"),
    Language("dje", "Zarma"),
    Language("zu", "Zulu")
)